# Generated by Django 3.2.5 on 2021-08-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('second_name', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('0', 'Binary')], default='female', max_length=1)),
                ('company', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=12)),
                ('resume', models.FileField(upload_to='')),
                ('city', models.CharField(max_length=10)),
                ('profile', models.ImageField(upload_to='')),
                ('joining_date', models.DateField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
