# Generated by Django 3.2.5 on 2021-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='teachers_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
