# Generated by Django 3.2.5 on 2021-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=12)),
                ('course_code', models.CharField(max_length=12)),
                ('trainer_id', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
