# Generated by Django 3.2.5 on 2021-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer_id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
