# Generated by Django 3.2.5 on 2021-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(),
        ),
    ]
