# Generated by Django 3.2.5 on 2021-08-04 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_academic_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='guardians_contact',
            new_name='parents_contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='room_number',
            new_name='parents_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='City', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('0', 'Binary')], default='female', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_report',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda'), ('S', 'SouthSudan')], default='Kenya', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
