# Generated by Django 3.2.5 on 2021-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210804_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='health_report',
            field=models.FileField(blank=True, default='default.jpg', upload_to='health_report/'),
        ),
    ]
