# Generated by Django 3.2.5 on 2021-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210813_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='laptop_SerialNumber',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
